// generated by tools/build_pio_can.py -- do not edit
localparam integer CAN_CLKDIV  = 4;
localparam integer CAN_IMG_LEN = 1760;
localparam integer CAN_NA      = 52;   // strict bits of frame A (SOF .. CRC delimiter)
localparam integer CAN_NB      = 63;   // bits of frame B the testbench sends (SOF .. CRC delimiter)
localparam integer CAN_NEXP    = 33;   // LED_OUT writes the CPU makes
localparam [255:0] CAN_A_WIRE  = 256'hffebb68b57b60c48;   // bit i = level of wire bit i of frame A, ACK slot and tail
localparam [255:0] CAN_B_BITS  = 256'h6579e414120e0a54;   // bit i = bit i of frame B
reg [7:0] can_exp [0:32];
task load_can_expect;
    begin
        can_exp[0] = 8'hfc;
        can_exp[1] = 8'h48;
        can_exp[2] = 8'h0c;
        can_exp[3] = 8'hb6;
        can_exp[4] = 8'h57;
        can_exp[5] = 8'h8b;
        can_exp[6] = 8'hb6;
        can_exp[7] = 8'heb;
        can_exp[8] = 8'hff;
        can_exp[9] = 8'h00;
        can_exp[10] = 8'h00;
        can_exp[11] = 8'h00;
        can_exp[12] = 8'h00;
        can_exp[13] = 8'hc0;
        can_exp[14] = 8'hff;
        can_exp[15] = 8'hff;
        can_exp[16] = 8'hff;
        can_exp[17] = 8'h54;
        can_exp[18] = 8'h0a;
        can_exp[19] = 8'h0e;
        can_exp[20] = 8'h12;
        can_exp[21] = 8'h14;
        can_exp[22] = 8'he4;
        can_exp[23] = 8'h79;
        can_exp[24] = 8'he5;
        can_exp[25] = 8'h00;
        can_exp[26] = 8'h00;
        can_exp[27] = 8'h00;
        can_exp[28] = 8'hff;
        can_exp[29] = 8'hb8;
        can_exp[30] = 8'hff;
        can_exp[31] = 8'hff;
        can_exp[32] = 8'hff;
    end
endtask
