`timescale 1ns/1ps

// tb_pio_cpu_multi.v -- ONE flash image, ONE PIO state machine, THREE protocols in sequence.
//
// The image from tools/build_pio_multi.py makes the CPU reprogram PIO SM0 at run time:
//   1. UART TX  "Agil" on uo_out[0]                  (checked by a UART receiver, 32 clk/bit)
//   2. SPI mode 0, 0xA5 0x3C on MOSI=uo_out[0], SCK=uo_out[1]  (checked by an SPI slave)
//   3. I2C write C3 96 to 0x50 on uio[4]/uio[5]      (checked by an open-drain I2C slave)
// and finally executes EBREAK: the I2C STOP is generated by PIO with the CPU parked.
// It also checks that the three protocols ran strictly one after the other.

module tb_pio_cpu_multi;
    reg clk = 0;
    reg rst_n;
    reg [7:0] ui_in;
    wire [7:0] uo_out, uio_out, uio_oe;
    always #5 clk = ~clk;

    wire cs0 = uio_out[0], cs1 = uio_out[6], sck = uio_out[3], mosi = uio_out[1];
    wire miso_flash, miso_psram;
    wire miso_bus = (!cs0) ? miso_flash : (!cs1) ? miso_psram : 1'b0;

    // ---- open-drain I2C bus: uio[4] = SDA, uio[5] = SCL ----
    reg  slave_sda_low;
    wire m_sda_low = uio_oe[4] & ~uio_out[4];
    wire m_scl_low = uio_oe[5] & ~uio_out[5];
    wire sda = ~(m_sda_low | slave_sda_low);
    wire scl = ~m_scl_low;
    wire [7:0] uio_in = {2'b0, scl, sda, 1'b0, miso_bus, 2'b0};

    tt_um_agila32 dut (.ui_in(ui_in), .uo_out(uo_out), .uio_in(uio_in),
                       .uio_out(uio_out), .uio_oe(uio_oe), .ena(1'b1),
                       .clk(clk), .rst_n(rst_n));

    spi_ram_model u_flash (.cs_n(cs0), .sck(sck), .mosi(mosi), .miso(miso_flash));
    spi_ram_model u_psram (.cs_n(cs1), .sck(sck), .mosi(mosi), .miso(miso_psram));

    reg [7:0] image [0:2595];
    integer ci;
    initial begin
        $readmemh("pio_multi_flash_image.hex", image);
        for (ci = 0; ci < 2596; ci = ci + 1) u_flash.mem[ci] = image[ci];
    end

    task automatic boot_send_bit(input b);
        begin
            ui_in[0] = b; ui_in[1] = 0; repeat (200) @(posedge clk);
            ui_in[1] = 1;               repeat (200) @(posedge clk);
            ui_in[1] = 0;               repeat (200) @(posedge clk);
        end
    endtask
    task automatic boot_send_byte(input [7:0] b);
        integer bi;
        begin for (bi = 7; bi >= 0; bi = bi - 1) boot_send_bit(b[bi]); end
    endtask

    reg [7:0] stub_bytes [0:3];
    localparam integer STUB_LEN = 4;

    // ================= phase 1 monitor: UART receiver on uo_out[0] =================
    localparam integer SPB = 32;                       // 8 ticks x CLKDIV 4
    reg [7:0] u_rx [0:7];
    integer   u_n, u_frame_errs;
    time      t_uart_end;
    task automatic rx_byte;
        integer b; reg [7:0] d;
        begin
            @(negedge uo_out[0]);
            repeat (SPB/2) @(posedge clk);
            if (uo_out[0] !== 1'b0) u_frame_errs = u_frame_errs + 1;
            for (b = 0; b < 8; b = b + 1) begin repeat (SPB) @(posedge clk); d[b] = uo_out[0]; end
            repeat (SPB) @(posedge clk);
            if (uo_out[0] !== 1'b1) u_frame_errs = u_frame_errs + 1;
            u_rx[u_n] = d; u_n = u_n + 1;
        end
    endtask
    initial begin
        u_n = 0; u_frame_errs = 0; t_uart_end = 0;
        wait (dut.u_pio.own_q[0] === 1'b1);            // line is idle-high from here (no glitch)
        repeat (4) rx_byte;
        t_uart_end = $time;
    end

    // ================= phase 2 monitor: SPI mode-0 slave (sample MOSI on SCK rise) =================
    reg [7:0] s_rx [0:7];
    integer   s_n, s_bits;
    reg [7:0] s_sh;
    time      t_spi_first, t_spi_last;
    initial begin s_n = 0; s_bits = 0; s_sh = 0; t_spi_first = 0; t_spi_last = 0; end
    always @(posedge uo_out[1]) if (dut.u_pio.own_q[1] === 1'b1 && u_n == 4) begin
        if (t_spi_first == 0) t_spi_first = $time;
        t_spi_last = $time;
        s_sh = {s_sh[6:0], uo_out[0]};
        s_bits = s_bits + 1;
        if (s_bits == 8) begin s_rx[s_n] = s_sh; s_n = s_n + 1; s_bits = 0; end
    end

    // ================= phase 3 monitor: open-drain I2C slave, address 0x50 =================
    reg [7:0] i_rx [0:7];
    integer   i_n, starts, stops;
    reg       in_txn, first_byte, last_ack;
    integer   bitcnt;
    reg [7:0] shreg;
    time      t_i2c_start;
    initial begin
        slave_sda_low = 0; i_n = 0; starts = 0; stops = 0;
        in_txn = 0; bitcnt = 0; shreg = 0; first_byte = 0; last_ack = 0; t_i2c_start = 0;
    end
    always @(negedge sda) if (rst_n === 1'b1 && scl === 1'b1) begin
        starts = starts + 1; in_txn = 1; bitcnt = 0; shreg = 0; first_byte = 1; slave_sda_low = 0;
        t_i2c_start = $time;
    end
    always @(posedge sda) if (rst_n === 1'b1 && scl === 1'b1) begin
        stops = stops + 1; in_txn = 0; slave_sda_low = 0;
    end
    always @(posedge scl) if (in_txn) begin
        if (bitcnt < 8) begin shreg = {shreg[6:0], sda}; bitcnt = bitcnt + 1; end
        else            bitcnt = 9;
    end
    always @(negedge scl) if (in_txn) begin
        if (bitcnt == 8) begin
            i_rx[i_n] = shreg; i_n = i_n + 1;
            last_ack = first_byte ? (shreg[7:1] == 7'h50) : 1'b1;
            first_byte = 0;
            if (last_ack) slave_sda_low = 1;
        end else if (bitcnt == 9) begin
            slave_sda_low = 0; bitcnt = 0; shreg = 0;
        end
    end

    // ---- halt tracking ----
    reg halt_seen; integer stops_at_halt;
    initial begin halt_seen = 0; stops_at_halt = -1; end
    always @(posedge clk) if (dut.halted && !halt_seen) begin halt_seen = 1; stops_at_halt = stops; end

    integer errors, i;
    reg [7:0] exp_u [0:3];
    reg [7:0] exp_s [0:1];
    reg [7:0] exp_i [0:2];

    initial begin
        exp_u[0] = "A"; exp_u[1] = "g"; exp_u[2] = "i"; exp_u[3] = "l";
        exp_s[0] = 8'hA5; exp_s[1] = 8'h3C;
        exp_i[0] = 8'hA0; exp_i[1] = 8'hC3; exp_i[2] = 8'h96;
        $readmemh("flash_handoff_stub.hex", stub_bytes);
        errors = 0;
        ui_in = 8'h00;
        rst_n = 0; repeat (10) @(posedge clk); rst_n = 1;
        dut.u_mem.qspi_div_sel = 2'd0;
        repeat (3000) @(posedge clk);

        ui_in[2] = 1;
        repeat (20) @(posedge clk);
        boot_send_byte(STUB_LEN);
        for (ci = 0; ci < STUB_LEN; ci = ci + 1) boot_send_byte(stub_bytes[ci]);

        i = 0;
        while (stops == 0 && i < 3000000) begin @(posedge clk); i = i + 1; end
        repeat (200) @(posedge clk);

        // ---- phase 1
        for (i = 0; i < 4; i = i + 1) begin
            if (u_rx[i] !== exp_u[i]) begin errors = errors + 1; $display("FAIL: UART byte %0d = 0x%02x, expected 0x%02x", i, u_rx[i], exp_u[i]); end
        end
        if (u_n != 4 || u_frame_errs != 0) begin errors = errors + 1; $display("FAIL: UART frames=%0d framing errors=%0d", u_n, u_frame_errs); end
        else $display("PASS: phase 1 UART sent \"Agil\" (%0d frames, no framing errors)", u_n);

        // ---- phase 2
        if (s_n != 2) begin errors = errors + 1; $display("FAIL: SPI slave saw %0d bytes, expected 2", s_n); end
        for (i = 0; i < 2 && i < s_n; i = i + 1)
            if (s_rx[i] !== exp_s[i]) begin errors = errors + 1; $display("FAIL: SPI byte %0d = 0x%02x, expected 0x%02x", i, s_rx[i], exp_s[i]); end
        if (s_n == 2 && s_rx[0] === exp_s[0] && s_rx[1] === exp_s[1]) $display("PASS: phase 2 SPI mode 0 sent A5 3C");

        // ---- phase 3
        if (i_n != 3) begin errors = errors + 1; $display("FAIL: I2C slave saw %0d bytes, expected 3", i_n); end
        for (i = 0; i < 3 && i < i_n; i = i + 1)
            if (i_rx[i] !== exp_i[i]) begin errors = errors + 1; $display("FAIL: I2C byte %0d = 0x%02x, expected 0x%02x", i, i_rx[i], exp_i[i]); end
        if (starts != 1 || stops != 1) begin errors = errors + 1; $display("FAIL: I2C starts=%0d stops=%0d", starts, stops); end
        else if (i_n == 3 && i_rx[0] === exp_i[0] && i_rx[1] === exp_i[1] && i_rx[2] === exp_i[2])
            $display("PASS: phase 3 I2C wrote C3 96 to 0x50 (all ACKed, one START, one STOP)");

        // ---- ordering: same silicon, strictly one protocol after another
        if (!(t_uart_end != 0 && t_spi_first > t_uart_end && t_i2c_start > t_spi_last)) begin
            errors = errors + 1;
            $display("FAIL: phases overlapped (uart_end=%0t spi=%0t..%0t i2c_start=%0t)", t_uart_end, t_spi_first, t_spi_last, t_i2c_start);
        end else
            $display("PASS: UART, SPI and I2C ran strictly in sequence on the same state machine");

        if (!halt_seen || stops_at_halt != 0) begin errors = errors + 1; $display("FAIL: core must halt before the I2C STOP"); end
        else $display("PASS: core halted (EBREAK) before the I2C STOP; PIO finished it alone");

        if (errors == 0) $display("PASS tb_pio_cpu_multi: one image, one PIO, UART + SPI + I2C");
        else             $display("FAIL tb_pio_cpu_multi: %0d error(s)", errors);
        $finish;
    end

    initial begin
        #900000000;
        $display("TIMEOUT (uart=%0d spi=%0d i2c=%0d)", u_n, s_n, i_n);
        $finish;
    end
endmodule
