#!/usr/bin/env python3
"""gen_random_init.py -- list every state-holding register of tt_um_agila32 and write test/random_init.vh.

Why: on silicon the register file, RAM, PIO instruction memory and FIFO storage have no reset and start in an unknown
state, and simulation hides that because the RTL zeroes them in `initial` blocks (inside `ifndef SYNTHESIS`).
test/tb.v includes the file written here when it is compiled with -DRANDOM_INIT=<seed>; it then fills EVERY flip-flop
with random bits 1 ns after time 0, before the first clock edge that matters, so only rst_n can put the chip in a known state.

How: Yosys (proc + flatten, SYNTHESIS defined) gives the flip-flop outputs; every public alias of a flip-flop output is a
candidate; Icarus then rejects the aliases that are wires and not regs ("not a valid l-value"), and those lines are dropped.

Usage (from the repository root; needs yosys or yowasp-yosys, and iverilog):  python3 tools/gen_random_init.py
"""
import json, os, re, shutil, subprocess, sys, tempfile

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
SRC = ["tt_um_agila32.v", "rv32i_core.v", "mem.v", "qspi_shared_engine.v", "pio.v", "pio_sm.v", "pio_fifo.v"]
OUT = os.path.join(ROOT, "test", "random_init.vh")
TOP = "tt_um_agila32"
FLOPS = ("$dff", "$adff", "$dffe", "$adffe", "$sdff", "$sdffe", "$aldff", "$aldffe", "$dffsr", "$dffsre")


def yosys_cmd():
    for n in ("yosys", "yowasp-yosys"):
        if shutil.which(n):
            return n
    sys.exit("neither yosys nor yowasp-yosys found")


def flop_names():
    with tempfile.TemporaryDirectory() as tmp:
        # relative paths: the packaged yosys cannot always open absolute ones
        os.makedirs(os.path.join(tmp, "src"))
        for f in os.listdir(os.path.join(ROOT, "src")):
            shutil.copy(os.path.join(ROOT, "src", f), os.path.join(tmp, "src", f))
        files = " ".join("src/" + f for f in SRC)
        subprocess.run([yosys_cmd(), "-q", "-p",
                        f"read_verilog -sv -DSYNTHESIS -Isrc {files}; hierarchy -top {TOP}; proc; flatten; opt_clean; write_json flat.json"],
                       cwd=tmp, check=True)
        m = json.load(open(os.path.join(tmp, "flat.json")))["modules"][TOP]
    bit2names = {}
    for n, v in m["netnames"].items():
        if n.startswith("$") or n.startswith("\\$"):
            continue
        for b in v["bits"]:
            if isinstance(b, int):
                bit2names.setdefault(b, set()).add(n)
    names = set()
    for c in m["cells"].values():
        if c["type"] in FLOPS:
            for b in c["connections"]["Q"]:
                if isinstance(b, int):
                    names |= bit2names.get(b, set())
    return sorted(n.lstrip("\\") for n in names)


def compile_errors():
    cmd = ["iverilog", "-g2012", "-DRANDOM_INIT=1", "-I", os.path.join(ROOT, "src"), "-I", os.path.join(ROOT, "test"),
           "-o", os.devnull, os.path.join(ROOT, "test", "tb.v")] + [os.path.join(ROOT, "src", f) for f in SRC]
    r = subprocess.run(cmd, capture_output=True, text=True)
    return r.stderr


def main():
    names = flop_names()
    lines = [f"user_project.{n} = {{$random(seed), $random(seed)}};" for n in names]
    for _ in range(8):
        open(OUT, "w").write("// generated by tools/gen_random_init.py -- do not edit\n" + "\n".join(lines) + "\n")
        err = compile_errors()
        bad = {int(m.group(1)) - 2 for m in re.finditer(r"random_init\.vh:(\d+): error", err)}
        if not bad:
            if "error" in err.lower():
                sys.exit("compile errors not caused by random_init.vh:\n" + err)
            break
        lines = [l for i, l in enumerate(lines) if i not in bad]
    else:
        sys.exit("could not clean the list")
    print(f"wrote {OUT}: {len(lines)} register assignments")


if __name__ == "__main__":
    main()
